// The "quote of the day" pool for the banner at the top of every page.
// One is shown per day, working down the list and starting again at the top.
// To add your own, just add another line — keep the quote marks and comma.
export const QUOTES: string[] = [
  'A tidy shelf sells twice.',
  'Nobody ever rolled a natural 20 by standing still.',
  'Greet first, tidy second.',
  'The stock count you do today is the panic you skip on Friday.',
  'No question is daft. The one nobody asked usually is.',
  'Face the shelves like someone is about to photograph them.',
  'Slow is smooth, and smooth is fast.',
  'A good demo sells more than a good discount.',
  'Customers remember how you made them feel, not what you charged.',
  'Measure twice, cut once.',
  'Many hands make light work.',
  'Well begun is half done.',
  'The kettle is a team-building exercise.',
  'Roll with it — then write it in the day book.',
  'Nobody has ever regretted labelling something.',
  'A clean till drawer is a happy till drawer.',
  'Be the colleague you would want on a busy Saturday.',
  'Enthusiasm is contagious. So is a good mood.',
  'The rules are the rules, right up until a customer needs a friend.',
  'If the shop looks good, the day feels shorter.',
  'Learn one new game a month. It pays for itself.',
  'Answer the phone like the shop depends on it, because it does.',
  'A pre-order promised is a pre-order kept.',
  'Check the date. Then check it again.',
  'Small jobs done now are big jobs avoided later.',
  'Smile — they can hear it down the phone.',
  'Never let someone leave empty-handed and unhelped.',
  'Tomorrow’s easy shift is built at closing time tonight.',
  'Neat handwriting on a label is a love letter to your colleagues.',
  'If in doubt, ask. If still in doubt, ask louder.',
];
